name: Docker Image CI

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
    tags:
      - '*'  # Triggers on push to any tag
  pull_request:
    branches:
      - '**'  # Triggers on pull request to any branch
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Extract version from branch or tag
      run: |
        if [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
          echo "VERSION=$(echo '${{ github.ref_name }}' | sed 's/release\///')-beta" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
        fi

    - name: Build and push image
      uses: docker/build-push-action@v6
      env:
        REPO: ${{ github.repository }}
      with:
        platforms: linux/amd64
        push: true
        file: ./Dockerfile
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{env.REPO}}:${{ env.VERSION }}
        build-args: |
          NO_CACHE=true
